#!/usr/bin/dh-exec

[linux-amd64] zimaos-usb-creator-cli-x86_64.AppImage => /usr/bin/zimaos-usb-creator-cli
[linux-arm64] zimaos-usb-creator-cli-aarch64.AppImage => /usr/bin/zimaos-usb-creator-cli
[linux-armhf] zimaos-usb-creator-cli-armhf.AppImage => /usr/bin/zimaos-usb-creator-cli

src/linux/icon/rpi-imager.svg /usr/share/icons/hicolor/scalable/apps/

debian/com.icewhaletech.zimaos-usb-creator-cli.desktop /usr/share/applications/

